name: prml-project
channels:
  - defaults
dependencies:
  - python=3.11.14
  - ipykernel
  - jupyter
  - numpy
  - pandas
  - scikit-learn==1.7.2
  - imbalanced-learn
  - seaborn
  - fastapi
  - uvicorn
  - pydantic
  - joblib
  - pytest
  - pip
  - pip:
      - xgboost
      - lightgbm
      - shap
